[package]
name = "postgres"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"

[features]
default = ["runtime"]

runtime = ["tokio-postgres/runtime", "tokio", "lazy_static", "log"]

"with-bit-vec-0.5" = ["tokio-postgres/with-bit-vec-0.5"]
"with-chrono-0.4" = ["tokio-postgres/with-chrono-0.4"]
"with-eui48-0.4" = ["tokio-postgres/with-eui48-0.4"]
"with-geo-0.10" = ["tokio-postgres/with-geo-0.10"]
"with-serde_json-1" = ["tokio-postgres/with-serde_json-1"]
"with-uuid-0.7" = ["tokio-postgres/with-uuid-0.7"]

[dependencies]
bytes = "0.4"
fallible-iterator = "0.1"
futures = "0.1"
tokio-postgres = { version = "0.3", path = "../tokio-postgres", default-features = false }

tokio = { version = "0.1", optional = true }
lazy_static = { version = "1.0", optional = true }
log = { version = "0.4", optional = true }
